FROM golang:1.24.11-alpine AS builder

WORKDIR /app

COPY . .

RUN go build -o chat ./cmd/chat

FROM alpine:3.20

RUN apk add --no-cache wget

WORKDIR /app

COPY --from=builder /app/chat /app/chat

EXPOSE 8082

CMD ["/app/chat"]
