FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY . .

RUN go build -o auth ./cmd/auth

FROM alpine:3.20

RUN apk add --no-cache wget

WORKDIR /app

COPY --from=builder /app/auth /app/auth

EXPOSE 8081

CMD ["/app/auth"]
