FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY . .

RUN go build -o auth ./cmd/auth

FROM alpine:3.20

WORKDIR /app

COPY --from=builder /app/auth /app/auth

ENV AUTH_HTTP_PORT=8081

EXPOSE 8081

CMD ["/app/auth"]
