services:
  auth:
    build:
      context: ./backend
      dockerfile: Dockerfile.auth
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
      JWT_SECRET: ${JWT_SECRET}
      AUTH_HTTP_PORT: ${AUTH_HTTP_PORT}
    depends_on:
      - db
