services:
  chat:
    ports:
      - '8082:8082'
    build:
      context: ../backend
      dockerfile: Dockerfile.chat
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
      JWT_SECRET: ${JWT_SECRET}
      CHAT_HTTP_PORT: ${CHAT_HTTP_PORT}
      LOG_LEVEL: ${LOG_LEVEL}
      LOG_DIR: ${LOG_DIR}
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:8082/health',
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
