services:
  proxy:
    image: nginx:stable
    volumes:
      - ../infra/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../infra/proxy/certs/localhost+1.pem:/etc/nginx/certs/cert.pem:ro
      - ../infra/proxy/certs/localhost+1-key.pem:/etc/nginx/certs/key.pem:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - auth
      - chat
